### ISSUE TITLE
Posting sensor data to adafruit IO

### ISSUE THREAD

**Issue by huhjy** [linux-downey/Grove_w600#3]
Hi, 

Thanks for the updated example. I'm using an arduino nano with temperature/humidity sensor, dust sensor, and voc sensor. In the example code, it seems like the wifi.httpPost allows you to push char values to adafruit IO. Is there a way to push sensor data collected as float values instead? Also is there a way to push multiple float values to different feeds?

**Comment by Hansen0314** [comment]
Hi there:
  Sorry, It is difficult for us to do this thing. I say there maybe exist some solution at [adafruitIO](https://io.adafruit.com/).
